### ISSUE TITLE
Add Filter Option to First Page

### ISSUE THREAD

**Issue by isuravishwa99** [sajithapislk/Vishwa---Cruise-Line-Reservation-System#20]
අයියේ මෙතැනට අර ෆිල්ටර් කරන option එක දාලා,
 හරි මෙතන මොකක් හරි සර්ච් කරොත්  අර පේජ් එකට රීඩිරෙක් වෙන විදිහට දාමුු

![image](https://github.com/user-attachments/assets/de124e98-4ebf-49a6-b4e6-9e206c423c93)

**Comment by sajithapislk** [comment]
51572b1f37025ac6079f067413cff51dc48ff12d
