### ISSUE TITLE
Remove cruise agent Email And Pw adding

### ISSUE THREAD

**Issue by isuravishwa99** [sajithapislk/Vishwa---Cruise-Line-Reservation-System#5]
http://127.0.0.1:8000/admin/cruise-company/create

Remove cruise agent Email And Pw adding from Cruise Company Create interface

![Screenshot 2024-10-13 112337](https://github.com/user-attachments/assets/9e805797-c023-4739-bc26-11a3b307875d)

**Comment by sajithapislk** [comment]
@isuravishwa99 it's browser default bro. when use save email password in browser the data auto filled up
