### ISSUE TITLE
User login need to redirect main interface 

### ISSUE THREAD

**Issue by isuravishwa99** [sajithapislk/Vishwa---Cruise-Line-Reservation-System#6]
http://127.0.0.1:8000/dashboard

User login need to redirect main interface not for dashboard

![fds](https://github.com/user-attachments/assets/caab93ce-ffe1-4a4f-9b3a-0f3459038512)

**Comment by sajithapislk** [comment]
f765b54efd5c6f21beef71edd35021977bb39688
