### ISSUE TITLE
Cuise Agent Details Dlt Not Working

### ISSUE THREAD

**Issue by isuravishwa99** [sajithapislk/Vishwa---Cruise-Line-Reservation-System#7]
Cruise Company Agent User Details Delete Funtion Not Working

![Screenshot 2024-10-13 113555](https://github.com/user-attachments/assets/ac4cd027-d6e9-48f2-acaa-2b239505bf21)
![Screenshot 2024-10-13 113605](https://github.com/user-attachments/assets/42edc485-3938-48d8-a37b-90e92d64340d)

**Comment by sajithapislk** [comment]
9a0cb279bd9253f40d21fb6df9dd9abb5fbd5b57
